---

- name: Ensure spamfilter is installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - amavisd-new
    - clamav-freshclam
    - clamav
    - spamassassin
    - clamav-daemon
    - sa-compile

- name: Enable and start service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - amavis
    - spamassassin
    - clamav-daemon
    - clamav-freshclam

- name: Write user configuration
  ansible.builtin.template:
    src: "50-user.j2"
    dest: "/etc/amavis/conf.d/50-user"
    mode: 0600
    owner: root
    group: root
  notify:
    - amavis







